builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - windows_amd64

archives:
  - replacements:
      darwin: macOS
    format_overrides:
      - goos: windows
        format: zip

brews:
  - tap:
      owner: junk1tm
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/junk1tm/goversion"
    description: "Easily switch between multiple Go versions"
    license: "MIT"
