name: checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    uses: go-simpler/.github/.github/workflows/test.yml@main
    with:
      go-versions: '[ "stable" ]' # go/version package available since 1.22
  lint:
    uses: go-simpler/.github/.github/workflows/lint.yml@main
  vuln:
    uses: go-simpler/.github/.github/workflows/vuln.yml@main

  functional:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      # https://github.com/actions/setup-go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run functional tests
        run: |
          echo $PATH
          chmod +x test.sh
          ./test.sh ${{ matrix.os }}
