name: checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    uses: go-simpler/.github/.github/workflows/test.yml@main
    with:
      go-versions: '[ "stable" ]' # go/version package available since 1.22
  lint:
    uses: go-simpler/.github/.github/workflows/lint.yml@main
  vuln:
    uses: go-simpler/.github/.github/workflows/vuln.yml@main
